name: Build OpenWrt Package (BPI-R4)

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Package
        uses: openwrt/gh-action-sdk@v1
        env:
          # Banana Pi R4 (MT7988) için doğru mimari hedefi:
          ARCH: aarch64_cortex-a73
          FEEDNAME: custom_feed
          PACKAGES: xmm7360-usb-modeswitch

      - name: Upload Artifacts
        uses: actions/actions/upload-artifact@v4
        with:
          name: BPI-R4-xmm-package
          path: bin/packages/aarch64_cortex-a73/custom_feed/*.ipk
